name: Run Postman Tests

on:
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          npx newman run upload-test.postman_collection.json \
          -e correspondence-env.json \
          -d upload-data.csv \
          -r html --reporter-html-export report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: report.html
