name: Run Postman Tests

on:
  push:
    branches:
      - main

jobs:
  newman-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman and HTML Reporter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Postman collection
      run: |
        newman run upload-test.postman_collection.json \
          --environment correspondence-env.json \
          --iteration-data upload-data.csv \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export newman/report.html

    - name: Upload report artifact
      uses: actions/upload-artifact@v3
      with:
        name: HTML Report
        path: newman/report.html
